FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip

RUN pip install --no-cache-dir -r requirements.txt

COPY . .


CMD celery -A app beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler

