# Generated by Django 5.2.12 on 2026-06-25 20:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Nome da Conta')),
                ('value', models.FloatField(default=0, verbose_name='Valor')),
                ('categorie', models.CharField(choices=[('conta corrente', 'Conta Corrente'), ('dinheiro', 'Dinheiro'), ('poupanca', 'Poupança'), ('investimentos', 'Investimentos'), ('vale', 'VR/VA'), ('outros', 'Outros')], default='Conta Corrente', max_length=100, verbose_name='Categoria da Conta')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_account', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Conta',
                'verbose_name_plural': 'Contas',
                'ordering': ['-created_at'],
            },
        ),
    ]
