# Generated by Django 5.2.12 on 2026-07-17 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorie',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
    ]
