# Generated by Django 5.1.3 on 2024-12-02 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_rename_category_id_budgets_category_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Budgets',
        ),
    ]
