# Generated by Django 5.1.3 on 2024-12-02 02:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_rename_amount_transaction_value_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
    ]
