# Generated by Django 5.1.3 on 2024-12-02 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0005_remove_accounts_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.BooleanField(),
        ),
    ]
