# Generated by Django 5.1.3 on 2024-12-02 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0006_alter_categories_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='type',
        ),
    ]
