# Generated by Django 5.1.3 on 2024-12-02 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0007_remove_categories_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('Receita', 'Despesa')], default='', max_length=100),
        ),
    ]
