# Generated by Django 5.1.3 on 2024-12-02 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0008_categories_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=100),
        ),
    ]
