# Generated by Django 5.1.3 on 2024-12-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0010_rename_description_transaction_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='name',
            new_name='description',
        ),
    ]
