# Generated by Django 5.1.3 on 2024-12-04 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0011_rename_name_transaction_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Conta'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome da Categoria'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='type',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], max_length=100, verbose_name='Tipo de Categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_accounts', to='finances.accounts', verbose_name='Conta'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_categories', to='finances.categories', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='value',
            field=models.FloatField(verbose_name='Valor'),
        ),
    ]
