# Generated by Django 5.1.3 on 2024-12-04 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0012_alter_accounts_created_at_alter_accounts_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='Descrição'),
        ),
    ]
