# Generated by Django 5.1.3 on 2024-12-04 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0013_alter_transaction_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categories',
            name='type',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], on_delete=django.db.models.deletion.PROTECT, related_name='transaction_categories', to='finances.categories', verbose_name='Categoria'),
        ),
    ]
