# Generated by Django 5.1.3 on 2024-12-05 00:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0015_remove_categories_created_at_remove_categories_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='category',
            field=models.CharField(choices=[('Receita', 'Receita'), ('Despesa', 'Despesa')], default='', max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_categories', to='finances.categories', verbose_name='Categoria'),
        ),
    ]
