# Generated by Django 5.1.3 on 2024-12-16 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0016_categories_category_alter_transaction_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
