# Generated by Django 5.1.3 on 2024-12-16 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0017_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Criado em'),
        ),
    ]
