# Generated by Django 5.1.3 on 2025-03-29 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0018_alter_transaction_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accounts',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at']},
        ),
    ]
