# Generated by Django 5.1.3 on 2025-04-02 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0019_alter_accounts_options_alter_transaction_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='category',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
    ]
