# Generated by Django 5.1.3 on 2025-04-25 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0022_alter_categorie_options_account_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='account',
            options={'ordering': ['-created_at'], 'verbose_name': 'Conta', 'verbose_name_plural': 'Contas'},
        ),
        migrations.AlterModelOptions(
            name='categorie',
            options={'ordering': ['-created_at'], 'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorias'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'ordering': ['-created_at'], 'verbose_name': 'Transação', 'verbose_name_plural': 'Transações'},
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='account',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='Nome da Conta'),
        ),
        migrations.AlterField(
            model_name='categorie',
            name='category',
            field=models.CharField(max_length=100, unique=True, verbose_name='Categoria'),
        ),
    ]
