# Generated by Django 5.1.3 on 2025-04-25 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0023_alter_account_options_alter_categorie_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='user',
        ),
    ]
