# Generated by Django 5.1.3 on 2025-04-30 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0028_alter_transaction_user_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Vencimento'),
        ),
    ]
