# Generated by Django 5.1.3 on 2025-05-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0029_transaction_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='due_date',
            field=models.DateField(verbose_name='Data de Vencimento'),
        ),
    ]
