# Generated by Django 5.2.5 on 2025-09-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0031_account_user_categorie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número de telefone (ex: 11999999999)', max_length=15, null=True, verbose_name='Telefone'),
        ),
    ]
