# Generated by Django 5.2.5 on 2025-09-03 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0032_alter_profile_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(default='', help_text='Número de telefone (ex: 11999999999)', max_length=15, verbose_name='Telefone'),
        ),
    ]
