# Generated by Django 5.2.5 on 2025-12-01 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0034_recipes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField(verbose_name='Valor')),
                ('description', models.CharField(blank=True, max_length=150, null=True, verbose_name='Descrição')),
                ('due_date', models.DateField(verbose_name='Data de Vencimento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de Criação')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Atualização')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues_accounts', to='finances.account', verbose_name='Conta')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='revenues_categorie', to='finances.categorie', verbose_name='Categoria')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_revenues', to=settings.AUTH_USER_MODEL, verbose_name='Receitas')),
            ],
            options={
                'verbose_name': 'Despesa',
                'verbose_name_plural': 'Despesas',
                'ordering': ['-created_at'],
            },
        ),
    ]
