# Generated by Django 5.2.5 on 2026-02-23 20:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0035_revenues'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenues',
            name='account',
        ),
        migrations.RemoveField(
            model_name='revenues',
            name='category',
        ),
        migrations.RemoveField(
            model_name='revenues',
            name='user',
        ),
        migrations.AddField(
            model_name='categorie',
            name='category_type',
            field=models.CharField(choices=[('revenue', 'Receita'), ('expense', 'Despesa')], default='revenue', max_length=10, verbose_name='Tipo de Categoria'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together={('user', 'category')},
        ),
        migrations.DeleteModel(
            name='Recipes',
        ),
        migrations.DeleteModel(
            name='Revenues',
        ),
    ]
