# Generated by Django 5.2.12 on 2026-05-31 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0036_remove_revenues_account_remove_revenues_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='categorie',
            field=models.CharField(choices=[('conta corrente', 'Conta Corrente'), ('dinheiro', 'Dinheiro'), ('poupanca', 'Poupança'), ('investimentos', 'Investimentos'), ('vale', 'VR/VA'), ('outros', 'Outros')], default='Conta Corrente', max_length=100, verbose_name='Categoria da Conta'),
        ),
        migrations.AddField(
            model_name='account',
            name='value',
            field=models.FloatField(default=0, verbose_name='Valor'),
        ),
    ]
