# Generated by Django 5.2.12 on 2026-06-25 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('categories', '0001_initial'),
        ('finances', '0037_account_categorie_account_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_accounts', to='accounts.account', verbose_name='Conta'),
        ),
        migrations.AlterUniqueTogether(
            name='categorie',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='categorie',
            name='user',
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction_categories', to='categories.categorie', verbose_name='Categoria'),
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Categorie',
        ),
    ]
